# Generated by Django 4.1.7 on 2023-03-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tragedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField(max_length=10000)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='articulo',
        ),
        migrations.RenameModel(
            old_name='autor',
            new_name='Autores',
        ),
        migrations.DeleteModel(
            name='articulo',
        ),
        migrations.AddField(
            model_name='articulos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tragedia.autores'),
        ),
    ]
